### ISSUE TITLE
Could the frequency and voltage be part of sfm3019_constants?

### ISSUE THREAD

**Issue by winkj** [Sensirion/python-sensorbridge-i2c-sfm#1]
On https://github.com/Sensirion/python-sensorbridge-i2c-sfm/blob/aef47c34a3960b55af09f4fc659510c812f7325e/quickstart.py#L20-L21 we're hardcoding bus frequency and voltage... could we pull this from the sensor constants (sfm3019_constants), potentially as a configuration object?

**Comment by psachs** [comment]
yes I think this makes sense. I like the approach to pull this from a configuration object with meaningful defaults.

**Comment by psachs** [comment]
took a while, but it's done in release 0.2.0
